name: Workshift System CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up JDK 8
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '8.0.382'
          distribution: 'zulu'
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: 8.4
          arguments: test
